#!/usr/bin/env bash
# forge_tailwind_config.sh  –  regenerate Tailwind v4 config
set -euo pipefail

echo "🔧  Backing up any existing Tailwind config …"
for f in tailwind.config.{js,cjs,mjs}; do
  [[ -f $f ]] && mv "$f" "${f}.bak.$(date +%s)"
done

echo "📝  Writing new tailwind.config.js (ES-module) …"
cat > tailwind.config.js <<'EOF'
/**
 * Tailwind v4 config – generated by Starforge 🛠️
 * Uses ESM export so it works with `"type":"module"` in package.json.
 */

import colors     from 'tailwindcss/colors.js';
import forms      from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import aspect     from '@tailwindcss/aspect-ratio';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',

  content: [
    './app/templates/**/*.html',
    './app/static/**/*.css',
    './app/static/js/**/*.js',
    './app/**/*.py',
  ],

  /*  keep dynamic classes produced in Jinja / JS  */
  safelist: [
    'font-bold', 'tracking-tight',
    'text-primary', 'bg-primary',
  ],

  /* ------------------------------------------------------ */
  theme: {
    /*  ⭐  1. full colour map (prevents theme(colors.*) errors) */
    colors: {
      ...colors,
      primary:         '#facc15',
      'primary-hover': '#e0b511',

      'bg-dark':    '#18181b',
      'text-light': '#fffbe7',
      'text-muted': 'rgba(255,255,255,0.7)',
    },

    /*  ⭐  2. everything else extends the defaults            */
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },

      boxShadow: {
        'gold-glow': '0 0 36px 0 rgb(250 204 21 / 0.8)',
      },

      borderRadius: {
        xl: '1rem',
      },

      /* animations */
      keyframes: {
        glow: {
          '0%':   { boxShadow: '0 4px 16px rgb(245 197 24 / 0.8), 0 0 8px rgb(245 197 24 / 0.5)' },
          '100%': { boxShadow: '0 6px 32px rgb(245 197 24 / 1), 0 0 24px rgb(245 197 24 / 0.8)' },
        },
      },
      animation: {
        glow: 'glow 2.8s ease-in-out infinite alternate',
      },

      /* transitions */
      transitionProperty: {
        colors:    'background-color,border-color,color,fill,stroke',
        shadow:    'box-shadow',
        transform: 'transform',
      },
      transitionDuration: {
        DEFAULT: '300ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'ease-in-out',
      },
    },
  },
  /* ------------------------------------------------------ */

  plugins: [forms, typography, aspect],
};
EOF
echo "✅  tailwind.config.js written."

# ------------------------------------------------------------------
echo "🏗  Building CSS bundle to verify …"
tailwindcss -c tailwind.config.js \
            -i app/static/globals.css \
            -o app/static/tailwind.min.css \
            --minify
echo "🎉  Build finished – check app/static/tailwind.min.css"
